animal:
  cat:
    - Barsik
    - Persik
    - Shusha
    - Fluff
  dog:
    - Sharik
    - Muchtar
    - Bobik
    - Cooper
  tiger:
    - Swift
    - Sonic
    - Nimble
    - Fleet
  shark:
    - Cindy
    - Sharkigator
    - Werner
    - Mr.Fish